version: 2.1
orbs:
  node: circleci/node@4.0.0
  cypress: cypress-io/cypress@1.16.1

jobs:
  run-build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  run-unit-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn install
      - run: yarn test -u

workflows:
  all-the-things:
    jobs:
      - run-build
      - run-unit-tests
      - cypress/install:
          name: run-cypress-build
          yarn: true
          build: yarn build
      - cypress/run:
          name: start-storybook
          yarn: true
          start: yarn storybook
          wait-on: 'http://localhost:6006'
      - cypress/run:
          name: run-integration-tests
          yarn: true
          start: yarn cy:run
