version: 2.1
orbs:
  node: circleci/node@4.0.0
  cypress: cypress-io/cypress@1.16.1
  codecov: codecov/codecov@1.1.1

jobs:
  run-build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  run-unit-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn install
      - run: yarn test -u

  collect-coverage:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:codecov
      - codecov/upload:
          file: './coverage/clover.xml'
          token: 8bb8c5f2-114f-4cea-b659-61af247109fd

workflows:
  all-the-things:
    jobs:
      - collect-coverage
      - run-build
      - run-unit-tests
      - cypress/install:
          name: cypress-install
          yarn: true
      - cypress/run:
          name: start-storybook-and-test
          yarn: true
          build: yarn build
          requires:
            - cypress-install
          start: yarn storybook
          wait-on: 'http://localhost:6006'
