version: 2.1
orbs:
  node: circleci/node@3.0.1
  cypress: cypress-io/cypress@1.16.1

jobs:
  run-build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  run-unit-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn install
      - run: yarn test -u

workflows:
  all-the-things:
    jobs:
      - cypress/install:
          yarn: true
      - cypress/run:
          yarn: true
          build: yarn build
          requires:
            - cypress/install
          yarn: true
          start: yarn cy:pipeline
